# permissions for end users to view prides.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pride-viewer-role
rules:
- apiGroups:
  - inflion.inflion.com
  resources:
  - prides
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - inflion.inflion.com
  resources:
  - prides/status
  verbs:
  - get
